// GENERATED by scripts/bake-darcula.mjs — DO NOT EDIT BY HAND.
// "Compensated Darcula": JetBrains' Darcula hues, lightness re-solved through Delta's
// two-lobe Helmholtz-Kohlrausch apparent-lightness model so every salience tier reads
// level. Baked to static hex (zero runtime calc). Re-bake: `node scripts/bake-darcula.mjs`.
// H-K model: here.build/docs/thinking/raw-data/design-science/helmholtz-kohlrausch-models.md
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import type { Extension } from "@codemirror/state";
import { EditorView } from "@codemirror/view";
import { tags } from "@lezer/highlight";

const highlightStyle = HighlightStyle.define([
  { tag: [tags.definitionKeyword, tags.controlKeyword, tags.keyword, tags.operatorKeyword, tags.moduleKeyword], color: "#c1712c" }, // differentiate aL≈0.62 h57 -> L0.626
  { tag: [tags.definition(tags.variableName), tags.function(tags.variableName)], color: "#fec56c" }, // anchor aL≈0.85 h77 -> L0.858
  { tag: [tags.variableName, tags.name], color: "#abb7c3" }, // baseline aL≈0.77 h250 -> L0.774
  { tag: [tags.string, tags.docString, tags.character], color: "#779465" }, // differentiate aL≈0.62 h134 -> L0.631
  { tag: [tags.number, tags.integer, tags.float], color: "#6190b3" }, // differentiate aL≈0.62 h242 -> L0.632
  { tag: [tags.bool, tags.atom, tags.null], color: "#6190b3" }, // differentiate aL≈0.62 h242 -> L0.632
  { tag: [tags.propertyName, tags.labelName], color: "#9b78ac" }, // differentiate aL≈0.62 h314 -> L0.625
  { tag: [tags.comment, tags.lineComment, tags.blockComment], color: "#717171" }, // recede aL≈0.55 h140 -> L0.550
  { tag: tags.docComment, color: "#58824f" }, // recede aL≈0.55 h140 -> L0.562
  { tag: tags.meta, color: "#9f806a" }, // differentiate aL≈0.62 h57 -> L0.622
  { tag: [tags.paren, tags.squareBracket], color: "#717171" }, // recede aL≈0.55 h250 -> L0.550
  { tag: tags.brace, color: "#856d5b", fontStyle: "italic" }, // recede aL≈0.55 h57 -> L0.552
  { tag: [tags.compareOperator, tags.logicOperator, tags.controlOperator, tags.arithmeticOperator, tags.operator], color: "#b57748", fontStyle: "italic" }, // differentiate aL≈0.62 h57 -> L0.624
  { tag: tags.processingInstruction, color: "#e9bdff", fontWeight: "600" }, // anchor aL≈0.85 h314 -> L0.858
  { tag: tags.contentSeparator, color: "#806e61" }, // recede aL≈0.55 h57 -> L0.551
  { tag: tags.bracket, color: "#717171" }, // recede aL≈0.55 h250 -> L0.550
  { tag: tags.content, color: "#b4b4b4" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: [tags.heading, tags.strong], color: "#b4b4b4", fontWeight: "600" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: tags.emphasis, color: "#b4b4b4", fontStyle: "italic" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: tags.invalid, color: "#bd413f" }, // alarm aL≈0.53 h25 -> L0.549
]);

const chrome = EditorView.theme(
  {
    "&": { color: "#A9B7C6", backgroundColor: "oklch(0.2 0 211)" },
    ".cm-content": { caretColor: "#BBBBBB" },
    "&.cm-focused .cm-cursor": { borderLeftColor: "#BBBBBB" },
    "&.cm-focused .cm-selectionBackground, .cm-selectionBackground, ::selection": {
      backgroundColor: "#214283",
    },
    ".cm-activeLine": { backgroundColor: "#323232" },
    ".cm-gutters": { backgroundColor: "oklch(0.2 0 211)", color: "#606366", border: "none" },
    ".cm-activeLineGutter": { backgroundColor: "#323232" },
  },
  { dark: true },
);

/** Compensated-Darcula theme: editor chrome + H-K-leveled syntax highlighting. */
export const darcula: Extension = [chrome, syntaxHighlighting(highlightStyle)];
