// GENERATED by scripts/bake-darcula.mjs — DO NOT EDIT BY HAND.
// "Compensated Darcula": JetBrains' Darcula hues, lightness re-solved through the
// Nayatani 3-harmonic H-K model (Delta / postcss-oklch-plus) so every salience tier
// reads level. Baked to static hex. Re-bake: `node scripts/bake-darcula.mjs`.
// H-K SSOT: here.build/docs/thinking/raw-data/design-science/helmholtz-kohlrausch-models.md
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import type { Extension } from "@codemirror/state";
import { EditorView } from "@codemirror/view";
import { tags } from "@lezer/highlight";

const highlightStyle = HighlightStyle.define([
  { tag: [tags.definitionKeyword, tags.controlKeyword, tags.keyword, tags.operatorKeyword, tags.moduleKeyword], color: "#bb6b25" }, // differentiate aL≈0.62 h57 -> L0.607
  { tag: [tags.definition(tags.variableName), tags.function(tags.variableName)], color: "#f8bf66" }, // anchor aL≈0.85 h77 -> L0.840
  { tag: [tags.variableName, tags.name], color: "#a9b5c1" }, // baseline aL≈0.77 h250 -> L0.767
  { tag: [tags.string, tags.docString, tags.character], color: "#728e60" }, // differentiate aL≈0.62 h134 -> L0.613
  { tag: [tags.number, tags.integer, tags.float], color: "#5b89ad" }, // differentiate aL≈0.62 h242 -> L0.612
  { tag: [tags.bool, tags.atom, tags.null], color: "#5b89ad" }, // differentiate aL≈0.62 h242 -> L0.612
  { tag: [tags.propertyName, tags.labelName], color: "#9673a7" }, // differentiate aL≈0.62 h314 -> L0.609
  { tag: [tags.comment, tags.lineComment, tags.blockComment], color: "#717171" }, // recede aL≈0.55 h140 -> L0.550
  { tag: tags.docComment, color: "#527c49" }, // recede aL≈0.55 h140 -> L0.542
  { tag: tags.meta, color: "#9c7e68" }, // differentiate aL≈0.62 h57 -> L0.615
  { tag: [tags.paren, tags.squareBracket], color: "#717171" }, // recede aL≈0.55 h250 -> L0.550
  { tag: tags.brace, color: "#836b5a", fontStyle: "italic" }, // recede aL≈0.55 h57 -> L0.546
  { tag: [tags.compareOperator, tags.logicOperator, tags.controlOperator, tags.arithmeticOperator, tags.operator], color: "#b07344", fontStyle: "italic" }, // differentiate aL≈0.62 h57 -> L0.610
  { tag: tags.processingInstruction, color: "#e4b0ff", fontWeight: "600" }, // anchor aL≈0.85 h314 -> L0.832
  { tag: tags.contentSeparator, color: "#7f6d60" }, // recede aL≈0.55 h57 -> L0.547
  { tag: tags.bracket, color: "#717171" }, // recede aL≈0.55 h250 -> L0.550
  { tag: tags.content, color: "#b4b4b4" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: [tags.heading, tags.strong], color: "#b4b4b4", fontWeight: "600" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: tags.emphasis, color: "#b4b4b4", fontStyle: "italic" }, // baseline aL≈0.77 h250 -> L0.770
  { tag: tags.invalid, color: "#af3434" }, // alarm aL≈0.53 h25 -> L0.511
]);

const chrome = EditorView.theme(
  {
    "&": { color: "#A9B7C6", backgroundColor: "oklch(0.2 0 211)" },
    ".cm-content": { caretColor: "#BBBBBB" },
    "&.cm-focused .cm-cursor": { borderLeftColor: "#BBBBBB" },
    "&.cm-focused .cm-selectionBackground, .cm-selectionBackground, ::selection": {
      backgroundColor: "#214283",
    },
    ".cm-activeLine": { backgroundColor: "#323232" },
    ".cm-gutters": { backgroundColor: "oklch(0.2 0 211)", color: "#606366", border: "none" },
    ".cm-activeLineGutter": { backgroundColor: "#323232" },
  },
  { dark: true },
);

/** Compensated-Darcula theme: editor chrome + H-K-leveled syntax highlighting. */
export const darcula: Extension = [chrome, syntaxHighlighting(highlightStyle)];
